[tool.poetry]
name = "riot-api"
version = "0.1.0"
description = ""
authors = ["Yves Kleny <yves.kleny.1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
ipykernel = "^6.29.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
